# Generated by Django 4.2.16 on 2024-11-26 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteword',
            name='learning_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 2, 46, 5, 240865, tzinfo=datetime.timezone.utc)),
        ),
    ]
