# Generated by Django 4.2.16 on 2024-11-26 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_favoriteword_learning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteword',
            name='learning_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 11, 51, 21, 693911, tzinfo=datetime.timezone.utc)),
        ),
    ]
